export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGOUT_USER = "LOGOUT_USER";
export const CLEAR_AUTH_STATE = "CLEAR_AUTH_STATE";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const REGISTER_LOADING = "REGISTER_LOADING";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";

export const SELECT_CHAT = "SELECT_CHAT";